sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - 7.0

matrix:
  allow_failures:
    - rvm: hhvm

before_install:
    - pip install --user codecov

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --dev

script:
    - vendor/bin/phpunit --coverage-text --bootstrap vendor/autoload.php --coverage-clover=coverage.xml

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then codecov; fi

cache:
    directories:
        - $HOME/.composer/cache